### ISSUE TITLE
Package breaks sitemap?

### ISSUE THREAD

**Issue by jakob-fuchs** [Mnkras/php_debugbar#2]
I am getting a parse error on the sitemap page located at /dashboard/sitemap/full. This happens when I install this package and the error gets resolved once I uninstall it (I used a fresh install and there were no other packages installed).

This happens in 7.5 as well as 7.5.1.

Here is the output from the Google Chrome console:

``` javascript
21:55:0.985 - Dynatree._create(): version='$Version:$', debugLevel=2.
21:55:0.999 - Guessing imagePath from 'http://localhost/health_food/concrete/js/dynatree.js': 'http://localhost/health_food/concrete/js/skin/'
21:55:1.6 - DynaTree.persistence: Object
21:55:1.13 - Dynatree._load(): read tree structure...
21:55:1.16 - Dynatree._init(): send Ajax request...
21:55:1.17 - Class.create.removeChildren(false)
21:55:1.24 - Dynatree._load(): render nodes...
21:55:1.25 - Dynatree._load(): bind events...
21:55:1.27 - Dynatree._load(): postInit...
21:55:1.30 - Dynatree._init(): done.
21:55:1.31 - ui.dynatree._init() was called; no current default functionality.
21:55:1.489 - appendAjax failed: parsererror :
 Object {readyState: 4, responseText: "<link rel="stylesheet" type="text/css" href="http:…bpages":1,"canAddExternalLinks":1,"children":[]}]", status: 200, statusText: "OK"}abort: (a){var b=a||u;return i&&i.abort(b),x(0,b),this}always: (){return e.done(arguments).fail(arguments),this}complete: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}done: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}error: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}fail: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}getAllResponseHeaders: (){return 2===t?f:null}getResponseHeader: (a){var b;if(2===t){if(!j){j={};while(b=Cb.exec(f))j[b[1].toLowerCase()]=b[2]}b=j[a.toLowerCase()]}return null==b?null:b}overrideMimeType: (a){return t||(k.mimeType=a),this}pipe: (){var a=arguments;return m.Deferred(function(c){m.each(b,function(b,f){var g=m.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&m.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}progress: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}promise: (a){return null!=a?m.extend(a,d):d}readyState: 4responseText: "<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/css/font-awesome.min.css">↵<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/highlightjs/styles/github.css">↵<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/debugbar.css">↵<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/widgets.css">↵<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/openhandler.css">↵<link rel="stylesheet" type="text/css" href="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/widgets/sqlqueries/widget.css">↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/jquery/dist/jquery.min.js"></script>↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/highlightjs/highlight.pack.js"></script>↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/debugbar.js"></script>↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/widgets.js"></script>↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/openhandler.js"></script>↵<script type="text/javascript" src="http://localhost/health_food/packages/php_debugbar/vendor/maximebf/debugbar/src/DebugBar/Resources/widgets/sqlqueries/widget.js"></script>↵<script type="text/javascript">jQuery.noConflict(true);</script>↵↵[{"title":"Home","link":"http:\/\/localhost\/health_food\/index.php","isLazy":true,"iconClass":"fa fa-home","addClass":"ccm-page-home","cAlias":false,"isInTrash":false,"numSubpages":"11","isTrash":false,"cID":"1","key":"1","canEditPageProperties":1,"canEditPageSpeedSettings":1,"canEditPagePermissions":1,"canEditPageDesign":true,"canEditPageType":1,"canViewPageVersions":1,"canDeletePage":1,"canAddSubpages":1,"canAddExternalLinks":1,"children":[]}]"setRequestHeader: (a,b){var c=a.toLowerCase();return t||(a=s[c]=s[c]||a,r[a]=b),this}state: (){return c}status: 200statusCode: (a){var b;if(a)if(2>t)for(b in a)q[b]=[q[b],a[b]];else v.always(a[v.status]);return this}statusText: "OK"success: (){if(h){var d=h.length;!function f(b){m.each(b,function(b,c){var d=m.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&f(c)})}(arguments),b?e=h.length:c&&(g=d,j(c))}return this}then: (){var a=arguments;return m.Deferred(function(c){m.each(b,function(b,f){var g=m.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&m.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}__proto__: Object 
 SyntaxError: Unexpected token <
    at Object.parse (native)
    at m.parseJSON (http://localhost/health_food/concrete/js/jquery.js:5:15998)
    at Pb (http://localhost/health_food/concrete/js/jquery.js:5:18379)
    at x (http://localhost/health_food/concrete/js/jquery.js:5:21793)
    at XMLHttpRequest.m.ajaxTransport.send.b (http://localhost/health_food/concrete/js/jquery.js:5:26030)
```

**Comment by Mnkras** [comment]
Yea, I need to add in some additional checking to not add this stuff to the view if its a xhr request

**Comment by jakob-fuchs** [comment]
Thanks, it's working now ;)

**Comment by Mnkras** [comment]
Not a problem! (I made this addon and didn't really test it, just made sure c5 didn't crash and the toolbar showed up, so there are probably some other issues)
